cosign: false
verify: false
install:
  grub-entry-name: "Kairos"
  system:
    size: 3000
  recovery-system:
    size: 3000
upgrade:
  grub-entry-name: "Kairos"
  recovery-system:
    size: 3000
  system:
    size: 3000
reset:
  grub-entry-name: "Kairos"
  system:
    size: 3000

cloud-init-paths:
- /run/initramfs/cos-state
# - /run/initramfs/live