baseURL = 'https://kairos.io'
languageCode = 'en-us'
title = 'kairos documentation'
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/kairos-io/kairos/edit/master/docs/content/"
  description = "Documentation for kairos"
  author = "Ettore Di Giacinto"
  #themeVariant = "kairos"
  disableLandingPageButton = true
  themeVariant = "blue"
# For search functionality

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-solid fa-download'></i> Download"
identifier = "download"
url = "https://github.com/kairos-io/provider-kairos/releases"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-solid fa-download'></i> Download core (without k3s)"
identifier = "download-core"
url = "https://github.com/kairos-io/kairos/releases"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "github"
url = "https://github.com/kairos-io/kairos"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> Github discussions"
identifier = "discussions"
url = "https://github.com/kairos-io/kairos/discussions"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> Matrix chat"
identifier = "matrix"
url = "https://matrix.to/#/#kairos-io:matrix.org"
weight = 1

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> Libera chat"
identifier = "libera"
url = "https://web.libera.chat/#kairos"
weight = 1

[outputs]
home = [ "HTML", "RSS", "JSON"]

