name: Build core/light images

on: 
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC support
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
           variant: "light"
           with_cli: "true"
           with_provider: "false"
         - flavor: "opensuse"
           variant: "core"
           with_cli: "false"
           with_provider: "false"
         - flavor: "alpine"
           variant: "light"
           with_cli: "true"
           with_provider: "false"
         - flavor: "alpine"
           variant: "core"
           with_cli: "false"
           with_provider: "false"
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Quay Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Build  ðŸ”§
        env:
          VARIANT: ${{ matrix.variant }}
          FLAVOR: ${{ matrix.flavor }}
          IMAGE: quay.io/c3os/${{ matrix.variant }}-${{ matrix.flavor }}:latest
          WITH_CLI: ${{ matrix.with_cli }}
          WITH_PROVIDER: ${{ matrix.with_provider }}
        run: |
          ./earthly.sh +docker --WITH_K3S=false --IMAGE=${IMAGE} --VARIANT=${VARIANT} --FLAVOR=${FLAVOR} --C3OS_VERSION=latest --WITH_CLI=${WITH_CLI} --WITH_PROVIDER=${WITH_PROVIDER}
      - name: Push to quay
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          COSIGN_EXPERIMENTAL: 1
          IMAGE: quay.io/c3os/${{ matrix.variant }}-${{ matrix.flavor }}:latest
        run: | 
          docker push ${IMAGE}
          cosign sign ${IMAGE}