name: Reusable workflow that releases a flavor

on:
  workflow_call:
    inputs:
      base_image:
        required: true
        type: string
      model:
        required: false
        type: string
        default: "generic"
      variant:
        required: false
        type: string
        default: "core"
      arch:
        required: false
        type: string
        default: "amd64"
      kubernetes_version:
        required: false
        type: string
      kubernetes_distro:
        required: false
        type: string
      trusted_boot:
        required: false
        type: string
        default: "false"

jobs:
  release:
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    name: ${{ inputs.base_image }}
    permissions:
      id-token: write
      contents: write
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Split base image
        id: split
        run: |
          # All of this becuase opensuse/leap:15.6 has to be pushed to the opensuse repo instead of having opensuse-leap and opensuse-tumbleweed...
          base_image=$(echo "${{ inputs.base_image }}" | cut -d ':' -f 1)
          tag=$(echo "${{ inputs.base_image }}" | cut -d ':' -f 2 || echo 'latest')

          # Check if the base image contains a slash
          if [[ "$base_image" == *"/"* ]]; then
            # Split the base image into distro and sub-distro
            distro=$(echo "$base_image" | cut -d '/' -f 1)
            sub_distro=$(echo "$base_image" | cut -d '/' -f 2)
            # Combine sub-distro and tag
            tag="$sub_distro-$tag"
          else
            # Use the base image as the distro
            distro="$base_image"
          fi

          # Special case for nvidia as we build 2 different images and the base_image is our cached image
          # For release this makes no sense as we always build the base image anyway
          # TODO: Add support for nvidia-jetson-agx-orin in kairos-init so we can build it properly
          if [[ "${{ inputs.model }}" == "nvidia-jetson-agx-orin" ]]; then
            distro="ubuntu"
            tag="22.04"
          fi

          echo "flavor=$distro" >> $GITHUB_OUTPUT
          echo "flavor_release=$tag" >> $GITHUB_OUTPUT
      - name: Set Image Tag
        run: |
          # Replace + with - in kubernetes version as we use it in the image tag. Remove v as well
          sanitized_kubernetes_version=$(echo "${{ inputs.kubernetes_version }}" | sed 's/^v//; s/+/-/g')
          if [ -n "${sanitized_kubernetes_version}" ]; then
            echo "IMAGE_TAG=quay.io/kairos/${{ steps.split.outputs.flavor }}:${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}-${{ github.ref_name }}-${{ inputs.kubernetes_distro }}${sanitized_kubernetes_version}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}" >> $GITHUB_ENV
            echo "ISO_NAME=kairos-${{ steps.split.outputs.flavor }}-${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}-${{ github.ref_name }}${{ inputs.kubernetes_distro }}${sanitized_kubernetes_version}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=quay.io/kairos/${{ steps.split.outputs.flavor }}:${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}-${{ github.ref_name }}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}" >> $GITHUB_ENV
            echo "ISO_NAME=kairos-${{ steps.split.outputs.flavor }}-${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}-${{ github.ref_name }}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}" >> $GITHUB_ENV
          fi
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to Quay Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build the docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          file: images/Dockerfile
          platforms: linux/${{ inputs.arch }}
          load: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            BASE_IMAGE=${{ inputs.base_image }}
            MODEL=${{ inputs.model }}
            VARIANT=${{ inputs.variant }}
            KUBERNETES_VERSION=${{ inputs.kubernetes_version }}
            KUBERNETES_DISTRO=${{ inputs.kubernetes_distro }}
            TRUSTED_BOOT=${{ inputs.trusted_boot }}
            VERSION=${{ github.ref_name }}
      - name: Grype table
        uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
        with:
          image: ${{ env.IMAGE_TAG }}
          output-format: table
          severity-cutoff: critical
          add-cpes-if-none: true
          only-fixed: true
      - name: Grype sarif
        uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
        with:
          image: ${{ env.IMAGE_TAG }}
          output-format: sarif
          output-file: grype.sarif
          severity-cutoff: critical
          add-cpes-if-none: true
          only-fixed: true
      - name: Trivy
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: sarif
          output: trivy.sarif
          severity: CRITICAL
          limit-severities-for-sarif: true
      - name: Push the docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          file: images/Dockerfile
          platforms: linux/${{ inputs.arch }}
          push: true
          sbom: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            BASE_IMAGE=${{ inputs.base_image }}
            MODEL=${{ inputs.model }}
            VARIANT=${{ inputs.variant }}
            KUBERNETES_VERSION=${{ inputs.kubernetes_version }}
            KUBERNETES_DISTRO=${{ inputs.kubernetes_distro }}
            TRUSTED_BOOT=${{ inputs.trusted_boot }}
            VERSION=${{ github.ref_name }}
      - name: Sign image
        env:
          COSIGN_YES: true
        run: |
          cosign sign ${{ env.IMAGE_TAG }}
      - name: Build iso ðŸ“¦
        if: ${{ inputs.trusted_boot == 'false' && inputs.model == 'generic' }}
        run: |
          mkdir release
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD/release:/output \
          quay.io/kairos/auroraboot:latest --debug build-iso --output /output/ \
          --name ${{ env.ISO_NAME }} \
          docker:${{ env.IMAGE_TAG }}
      - name: Sign ISO sha files
        if: ${{ inputs.trusted_boot == 'false' && inputs.model == 'generic' }}
        env:
          COSIGN_YES: true
        run: |
          filename=$(ls release/*.iso.sha256)
          cosign sign-blob --yes --output-certificate="${filename}.pem" --output-signature="${filename}.sig" "${filename}"
      - name: Build RAW image
        if: ${{ inputs.model != 'rpi3' && inputs.model != 'generic' && inputs.model != 'nvidia-jetson-agx-orin' }}
        run: |
          docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD:/output \
          quay.io/kairos/auroraboot:latest \
          --debug \
          --set "disable_http_server=true" \
          --set "disable_netboot=true" \
          --set "container_image=${{ env.IMAGE_TAG }}" \
          --set "state_dir=/output" \
          --set "disk.raw=true"

          # Export image path to be used in the next step
          echo "RAW_ARTIFACT=$(ls *.raw|head -1)" >> $GITHUB_ENV
      - name: Create OCI artifact from RAW image
        if: ${{ inputs.model != 'rpi3' && inputs.model != 'generic' && inputs.model != 'nvidia-jetson-agx-orin' }}
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: .
          file: images/Dockerfile.img
          platforms: linux/${{ inputs.arch }}
          push: true
          tags: ${{ env.IMAGE_TAG }}-img
          build-args: |
            ARTIFACT=${{ env.RAW_ARTIFACT }}
      - name: Sign image
        if: ${{ inputs.model != 'rpi3' && inputs.model != 'generic' && inputs.model != 'nvidia-jetson-agx-orin'}}
        env:
          COSIGN_YES: true
        run: |
          cosign sign ${{ env.IMAGE_TAG }}-img
      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: |
            release/*.iso
            release/*.iso.sha256
            release/*.iso.sha256.sig
            release/*.iso.sha256.pem
      - uses: itxaka/sarif-filter@e5315c19bd49c5a4ad76310a2640b2586247d433 # v1
        with:
          input: grype.sarif
          output: grype.sarif
          severity: critical
      - uses: itxaka/sarif-filter@e5315c19bd49c5a4ad76310a2640b2586247d433 # v1
        with:
          input: trivy.sarif
          output: trivy.sarif
          severity: critical
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3
        with:
          sarif_file: 'trivy.sarif'
          category: ${{ steps.split.outputs.flavor }}-${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}
      - name: Upload Grype scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3
        with:
          sarif_file: 'grype.sarif'
          category: ${{ steps.split.outputs.flavor }}-${{ steps.split.outputs.flavor_release }}-${{ inputs.variant }}-${{ inputs.arch }}-${{ inputs.model }}${{ inputs.trusted_boot != 'false' && '-uki' || '' }}
